version: '3.7'

services:
  backend:
    build: ./simple-api
    container_name: my-api
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    container_name: my-db
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  httpd:
    build: ./http-server
    container_name: my-httpd
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./devops-front
    container_name: my-front-end
    networks:
      - my-network
    ports:
      - "8080:80"

networks:
  my-network:

volumes:
  db-volume:
