---
# tasks file for roles/app
- name: Wait for the database to be ready
  ansible.builtin.wait_for:
    host: postgresql://user:pwd@tp_devops_database:80/db
    state: started
    timeout: 60

- name: Run application container
  docker_container:
    name: tp_devops_simple_api
    image: azertyben2000/tp-devops-simple-api:latest
    env:
      DATABASE_URL: "postgresql://user:pwd@tp_devops_database:80/db"
    networks:
      - name: benjamin.courtois.takima.cloud

