---
# tasks file for roles/app
- name: Run application container
  docker_container:
    name: my-api
    image: azertyben2000/tp-devops-simple-api:latest
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://my-db:5432/db"
    networks:
      - name: my-network

