---
# tasks file for roles/app
- name: Run application container
  docker_container:
    name: my-api
    image: azertyben2000/tp-devops-simple-api:latest
    env:
      DATABASE_URL: "postgresql://user:pwd@my-db:80/db"
    networks:
      - name: my-network

