---
# tasks file for roles/proxy
- name: Run proxy container
  docker_container:
    name: my-proxy
    image: azertyben2000/tp-devops-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: my-network
