name: Docker Build and Push
on:
  workflow_run:
    workflows: ["Backend Tests"]
    branches: [main]
    types:
        - completed
            
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
            context: ./simple-api
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
            context: ./database
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
            context: ./http-server
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest 
        
                
